### ISSUE TITLE
Develop Video Client for City Hall Camera

### ISSUE THREAD

**Issue by mikebotts** [opensensorhub/geohsv#5]
###Subtasks

- [ ] configure video client for Cesium3D (2D fixed)
- [ ] convert PTZ tasking panel to dialog box
- [ ] test video and tasking with camera in lab
- [ ] create / find 3D models for cameras
- [ ] collect high-def terrain and 3D building models
- [ ] enable geolocation of footprint onto terrain/buildings
- [ ] enable 3D geolocation of video onto terrain
- [ ] enable 3D geolocation of video onto buildings as well
- [ ] connect location source selector to OSH server and demo
